
stages:

- build
- deploy


build:
  stage: build
  BASH_ENV: ~/.nvm/nvm.sh
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pwd
    - npm install

   
  
deploy:
  stage: deploy
  script:
    - whoami
