
stages:

- build
- deploy

 

build:
  environment:
        BASH_ENV: ~/.nvm/nvm.sh
  stage: build  
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pwd
    - npm install

   
  
deploy:
  stage: deploy
  script:
    - whoami
